name: -aula-05-artifact-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * 1-6' #A cada 15 min, de segunda a sabado

env:
  FILE_NAME: hello-server
  
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: List files in current directory
        run: ls -la

      - name: Make run.sh executable
        run: chmod +x ./run.sh

      - name: Run Script
        run: ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows

      - name: List files in current directory
        run: dir
